# Generated by Django 3.2.5 on 2021-07-24 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=30)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-85), django.core.validators.MaxValueValidator(85)])),
                ('long', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
