name: Android CI

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create secret key file
        env:
          SECRET_KEY: ${{ secrets.MAPGO_KEY }}
        run: |
          echo $SECRET_KEY >> ./client/apikey.properties
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        working-directory: ./client
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ./client/app/build/outputs/apk/debug
