name: Server Docker

on:  
  push:
    branches: [ server-docker ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "Ubuntu Latest"
            os: ubuntu-latest

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      working-directory: ./server
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mapgo_server:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}