name: Server CI

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: "Ubuntu Latest"
            os: ubuntu-latest

    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install packages
      run: sudo apt-get install -yq python3-setuptools
    - name: Run Python Test
      run: |
        pip3 install pycodestyle
        pycodestyle server